# This file is part of PolyTrend.
#
# PolyTrend is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PolyTrend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PolyTrend. If not, see <https://www.gnu.org/licenses/>.

# Form implementation generated from reading ui file 'view/gui.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_PolyTrend(object):
    def setupUi(self, PolyTrend):
        PolyTrend.setObjectName("PolyTrend")
        PolyTrend.resize(545, 960)
        self.centralwidget = QtWidgets.QWidget(parent=PolyTrend)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.app_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.app_logo.setMaximumSize(QtCore.QSize(500, 500))
        self.app_logo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.app_logo.setPixmap(QtGui.QPixmap("view/../assets/logo.png"))
        self.app_logo.setScaledContents(True)
        self.app_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.app_logo.setObjectName("app_logo")
        self.verticalLayout.addWidget(self.app_logo)
        self.heading = QtWidgets.QLabel(parent=self.centralwidget)
        self.heading.setObjectName("heading")
        self.verticalLayout.addWidget(self.heading)
        self.intro = QtWidgets.QLabel(parent=self.centralwidget)
        self.intro.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.intro.setObjectName("intro")
        self.verticalLayout.addWidget(self.intro)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.x_box = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.x_box.setMinimumSize(QtCore.QSize(61, 121))
        self.x_box.setObjectName("x_box")
        self.gridLayout.addWidget(self.x_box, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.y_box = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.y_box.setMinimumSize(QtCore.QSize(61, 121))
        self.y_box.setObjectName("y_box")
        self.gridLayout.addWidget(self.y_box, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.degree_box = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.degree_box.setMinimumSize(QtCore.QSize(41, 121))
        self.degree_box.setObjectName("degree_box")
        self.gridLayout.addWidget(self.degree_box, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 7, 1, 1)
        self.extrap_box = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.extrap_box.setObjectName("extrap_box")
        self.gridLayout.addWidget(self.extrap_box, 0, 8, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.csv_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.csv_button.setObjectName("csv_button")
        self.verticalLayout.addWidget(self.csv_button)
        self.plot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plot.setEnabled(False)
        self.plot.setObjectName("plot")
        self.verticalLayout.addWidget(self.plot)
        self.save_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.save_checkbox.setObjectName("save_checkbox")
        self.verticalLayout.addWidget(self.save_checkbox)
        PolyTrend.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=PolyTrend)
        self.statusbar.setObjectName("statusbar")
        PolyTrend.setStatusBar(self.statusbar)

        self.retranslateUi(PolyTrend)
        QtCore.QMetaObject.connectSlotsByName(PolyTrend)

    def retranslateUi(self, PolyTrend):
        _translate = QtCore.QCoreApplication.translate
        PolyTrend.setWindowTitle(_translate("PolyTrend", "PolyTrend"))
        self.heading.setText(_translate("PolyTrend", "This is PolyTrend - a simple clean way to create polynomial fits in data"))
        self.intro.setText(_translate("PolyTrend", "For CSV data, your data MUST be in the form x, f(x).\n"
"It is assumed that values on the same row correspond to the same point.\n"
"Make sure your CSV data starts with the axis labels in the first row.\n"
"Accepted delimiters are whitespace and line breaks in the text boxes below."))
        self.label_3.setText(_translate("PolyTrend", "x values"))
        self.label_4.setText(_translate("PolyTrend", "f(x) values"))
        self.label_5.setText(_translate("PolyTrend", "degrees"))
        self.label_6.setText(_translate("PolyTrend", "extrapolates (optional)"))
        self.csv_button.setText(_translate("PolyTrend", "Import csv file"))
        self.plot.setText(_translate("PolyTrend", "Fit polynomial"))
        self.save_checkbox.setText(_translate("PolyTrend", "Save to PNG"))
